server:
  port: 8100
spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-dyllis/all-reviews-config.git
          search-paths: dev,prod